# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PdeImgOSVAWPRYQ55YyznAm9soxxvRZJ
"""

import streamlit as st
from transformers import pipeline

# Load the sentiment analysis pipeline
@st.cache_resource  # caches model so it loads only once
def load_model():
    return pipeline("sentiment-analysis")

nlp = load_model()

st.title("🧠 Sentiment Analysis App")
st.write("Type a sentence and I’ll tell you if it’s Positive, Negative, or Neutral.")

# User input
user_input = st.text_area("Enter your text here:")

# Predict sentiment
if st.button("Analyze Sentiment"):
    if user_input.strip() != "":
        result = nlp(user_input)[0]
        label = result["label"]
        score = round(result["score"], 3)
        st.write(f"**Prediction:** {label} (Confidence: {score})")
    else:
        st.warning("⚠️ Please enter some text before analyzing.")